#!/system/xbin/ash
#
# copy initial data-partition contents

if [ ! -f /data/firstboot.done ]; then

    # copy initial data-setup
    rm -rf /cache/*
    rm -Rf /data/local/webapps
    rm -f /data/local/user.js
    cp -Rf /system/initial-data/* /data/

    # write to disk
    sync

    # mark setup as done
    touch /data/firstboot.done
    
fi

